# Production Settings
frontend.url=${FRONTEND_URL}
allowed.origins=${ALLOWED_ORIGINS}
spring.boot.admin.client.url=${FRONTEND_URL}/admin

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.tractorbhai=INFO

# Security
server.forward-headers-strategy=native
