# Development Settings
frontend.url=http://localhost:5173
allowed.origins=http://localhost:5173
spring.boot.admin.client.url=http://localhost:8080/admin

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.tractorbhai=DEBUG
