# Production Settings
# Using fallback values to prevent crash if environment variables are missing
frontend.url=${FRONTEND_URL:https://tractor-bhai.vikashkumar.site}
allowed.origins=${ALLOWED_ORIGINS:https://tractor-bhai.vikashkumar.site}
spring.boot.admin.client.url=${FRONTEND_URL:https://tractor-bhai.vikashkumar.site}/admin

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.tractorbhai=INFO

# Security
server.forward-headers-strategy=native
